name: Feature Request
description: Suggest an idea or improvement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much context as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: What problem does this feature solve? What use case drives it?
      placeholder: "I'm always frustrated when ..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you would like to see.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you have considered?

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the bot does this relate to?
      options:
        - Alert ingestion (Grafana / SNS / new source)
        - Discord embeds / threads
        - Slash commands
        - Alert routing config
        - Escalation / acknowledgment
        - HTTP API
        - Database / audit log
        - Docker / deployment
        - Other
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and this is not a duplicate.
          required: true
